**1.** Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Answer 1: NumPy provides efficient, multidimensional array objects and a collection of mathematical functions to operate on these arrays. It enhances Python's capabilities by offering fast computations, easy-to-use mathematical operations, and support for large datasets, significantly improving performance over standard Python lists.

**2**. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

Answer 2: np.mean() calculates the arithmetic mean of array elements, while np.average() allows for weighted averages by specifying a weights array. Use np.mean() for simple averages and np.average() when you need to account for different weights.

**3**. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Answer 3: For 1D arrays, use slicing [::-1] to reverse. For 2D arrays, use slicing along axes, e.g., array[::-1, :] to reverse rows and array[:, ::-1] to reverse columns.

Example 1D:

python
Copy code
import numpy as np
arr1d = np.array([1, 2, 3])
print(arr1d[::-1])  # Output: [3 2 1]
Example 2D:

python
Copy code
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[::-1, :])  # Output: [[4 5 6]
                         #          [1 2 3]]
print(arr2d[:, ::-1])  # Output: [[3 2 1]
                         #          [6 5 4]]
**4**. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Answer 4: Use the .dtype attribute of a NumPy array to determine its data type. Data types are crucial for memory efficiency and computational speed, as they define the size and precision of the data elements.

***5.*** Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Answer 5: ndarray is the core data structure in NumPy, representing N-dimensional arrays. Key features include support for vectorized operations, fixed-size elements, and broadcasting. Unlike Python lists, ndarrays offer efficient storage and operations for large datasets.

**6**. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Answer 6: NumPy arrays are faster and more memory-efficient than Python lists due to their fixed-size elements and contiguous memory allocation. They enable vectorized operations, reducing execution time compared to iterative operations on lists.

**7**. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Answer 7: vstack() stacks arrays vertically (row-wise), while hstack() stacks arrays horizontally (column-wise).

Example vstack():

python
Copy code
import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print(np.vstack((arr1, arr2)))  # Output: [[1 2]
                                #          [3 4]]
Example hstack():

python
Copy code
import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print(np.hstack((arr1, arr2)))  # Output: [1 2 3 4]

**8**. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

Answer 8: fliplr() flips arrays horizontally (left-to-right), while flipud() flips arrays vertically (up-to-down). fliplr() affects columns, and flipud() affects rows.

Example fliplr():

python
Copy code
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.fliplr(arr))  # Output: [[3 2 1]
                       #          [6 5 4]]
Example flipud():

python
Copy code
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.flipud(arr))  # Output: [[4 5 6]
                       #          [1 2 3]]
**9**. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Answer 9: array_split() divides an array into multiple sub-arrays. It handles uneven splits by distributing the extra elements across the first few sub-arrays.

Example:

python
Copy code
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.array_split(arr, 3))  # Output: [array([1, 2]), array([3, 4]), array([5])]

**10**. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Answer 10: Vectorization allows element-wise operations on arrays without explicit loops, improving performance. Broadcasting enables operations on arrays of different shapes by automatically expanding dimensions. Both concepts enhance efficiency by leveraging optimized C-level operations.